Store 및 Comment 구현
AlbertImKr/spring-boot-commerce-project pull request #5
Opened 2023-07-01 16:36 UTC by AlbertImKr

## 안녕하세요 . Chole 멘토님.😀
## 구현 내용

- Store
- Comment(미완성)
 
## 문제점
- Comment 에서 `@OneToOne ` 연결관계로 Comment 와 ChildComment를 연결하였는데 Fetch.Lazy를 사용할 수 없어서 매Comment를 호출 시 ParentComment 및 ChildComment를 호출해서 N+1 문제가 발생하고 있습니다.
     - ProductId 로 Comment 조회는 Root 및 childComment를 나눠서 호출하고 재연결하는 방법으로  해결하였습니다.
     - 하지만 Comment save 때 여전히 **N+1** 문제가 발생하고 있습니다. 시간이 부족하여 아직 해결하지 못하였습니다. 😭
     - refcator도 시간이 부족하여 못한 부분도 있습니다. 😭

2023-07-04 11:01 UTC, chloe-codes1 requested changes
고생 많으셨습니다!
DDD에 대한 이해도가 많이 올라온 것 같습니다 👍🏻 

몇가지 수정이 필요한 부분이 있어서,
리뷰 드린 내용 관련해서 한 번 고민해 보시고 다시 리뷰 요청주시면 감사하겠습니다!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/domain/Comment.java
> +    private UserId userId;
다른 aggregate의 aggregateId를 참조하는 부분은 [@AttributeOverride](https://jakarta.ee/specifications/persistence/2.2/apidocs/javax/persistence/attributeoverride) 를 사용하여 아래와 같이 표현할 수 있을 것 같습니다!

ex)
```java
@AttributeOverride(name = "id", column = @Column(name = "productId", nullable = false))
private ProductId productId
```

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/infra/presentation/CommentRepositoryImpl.java
> +package com.albert.commerce.comment.infra.presentation;
영구 저장소이므로 package명은 persistence가 적합할 것 같습니다!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/infra/presentation/imports/CommentJpaRepository.java
> +package com.albert.commerce.comment.infra.presentation.imports;
동일하게 package명 확인 부탁드립니다!

presentation -> persistence

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/apllication/CommentRequest.java
> +package com.albert.commerce.comment.command.apllication;
package name에 오탈자 확인 부탁드립니다!

apllication -> application

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/domain/Comment.java
> +    private String childCommentId;
parentCommentId 를 기준으로 부모-자식 댓글 tree를 그릴 수 있을 것이라
Comment가 `childCommentId` 를  알고 있지 않아도 될 것 같은데요,
중첩 댓글 조회를 위해 자식 댓글 개수 정도만 알고 있어도 될 것 같습니다!

해당 field는 제거하고, `childCount` field를 추가하는 것이 어떨지 검토 부탁드립니다!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/domain/Comment.java
> +    }
`childCommentId` field를 제거하면 이 method는 필요 없겠네요!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/ui/CommentController.java
> +                        commentRequest.detail(), parentCommentId));
CommentService에 method overloading을 하지 않고 단일 method로 구현한 후에,
Controller에서는 parentCommentId의 존재 여부를 검증 후 존재하지 않으면 null을 넘겨주는 형태로 간소화 할 수 있을 것 같습니다!

ex)
```java
(StringUtils.isNotBlank(request.parentId())) ? new CommentId(request.parentId()) : null))
```

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/apllication/CommentRequest.java
> +                             CommentId parentCommentId,
Request에서 ProductId와 같은 Value Object를 알지 않아도 될 것 같은데요,
String type을 사용하고, 실제로 사용하는 layer에서 new ProductId()로 생성하는 것이 좋을 것 같습니다!

CommentController에서 변환하면 되겠네요!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/ui/CommentController.java
> +    private final StoreDao storeDao;
`Presentation layer`에서는 HTTP 요청을 `Application layer`에서 필요로 하는 형식으로 **변환**해서 전달하는 역할을 하는데요,
Controller (Presentation layer)에서 Dao를 직접 참조하여 필요한 data를 모으는 것 보단, 
해당 역할을 Service (Application layer)에서 담당하는 것이 좋아보입니다!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/ui/CommentController.java
> +        Store store = storeDao.findById(commentRequest.storeId());
위의 리뷰 내용에 이어서, 여기에서는 형식을 변환하는 작업만 이루어지면 될 것 같습니다!

ex)
```java
var productId = new ProductId(commentRequest.productId());
```

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/apllication/CommentService.java
> +@Transactional
`@Transactional` annotation은 method 단위로 작성하는 컨벤션이 더 좋아보입니다!

1 transaction -> 1 aggregate change 규칙을 기억해주세요!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/apllication/CommentService.java
> +    private final CommentDao commentDao;
> CommentController에 남긴 리뷰를 먼저 보고 와주세요!

Service에서는 필요한 재료를 모으는 역할을 하는데요, 필요한 재료를 Repository를 통해 조회하면 됩니다!
필요한 domain의 Repository interface를 참조하는 형태로 구현하면 좋을 것 같습니다!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/apllication/CommentService.java
> +            String detail) {
위의 save() method로 parentCommentId 유무에 상관 없이 생성 로직을 수행하기 때문에
해당 method는 제거해도 좋습니다!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/apllication/CommentService.java
> +            CommentId parentCommentId) {
개인적으로 save는 좀 더 infra level (DB)에 어울리는 naming이라고 생각해서,
create 정도가 조금 더 적당하지 않을까 생각합니다!

(취향 차이가 있을 수 있으므로 고려만 해주세요 😄)

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/apllication/CommentService.java
> +        parentComment.updateChildCommentId(comment.getCommentId());
앞의 리뷰에서 말씀드렸듯이 해당 로직은 제거해도 좋을 것 같습니다!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/command/application/DeleteOrderRequest.java
> +public record DeleteOrderRequest(OrderId orderId,
동일하게 Request에서는 String으로 값을 가져오고, Controller에서 new OrderId로 생성하여 타입을 변환하는 형태로 변경하면 좋을 것 같습니다!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/command/application/OrderRequest.java
> +        List<ProductId> productsId,
동일하게 ProductId -> String으로 변경 고려해주세요!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/command/domain/Order.java
> +@Table(name = "\"order\"")
보통 table명은 복수형으로 표현하고는 하는데요 (ex. `orders`)
이참에 전체 테이블명을 복수형으로 변경하면 escape 처리하지 않아도 될 것 같네요!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/command/domain/Order.java
> +    private StoreId storeId;
Comment entity에 남겨둔 리뷰처럼 [@AttributeOverride](https://jakarta.ee/specifications/persistence/2.2/apidocs/javax/persistence/attributeoverride) 사용을 고려해 주세요!

2023-07-04 11:01 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/command/domain/Order.java
> +    private List<Product> products;
고민이 필요한 부분일 것 같은데요,
JPA 객체 모델링이 필요할지를 고민해야 할 것 같고,
productIds가 아닌 products 객체를 들고 있어야 하는지 고민해 보면 좋을 것 같습니다!

2023-07-04 11:16 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/domain/Comment.java
> +    private String parentCommentId;
@AttributeOverride(name = "id", column = @Column(name = "parentCommentId")
private String parentCommentId;

2023-07-04 11:27 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/command/apllication/CommentService.java
> +        Comment parentComment = commentDao.findById(parentCommentId);
parentCommentId가 null 일때의 분기를 이곳에 추가해주세요!

2023-07-07 07:03 UTC, AlbertImKr commented
안녕하세요 . Chloe 멘토님
리뷰 반영 했습니다.

- Domain Controller에서만 다른 Domain Facade를 참조하고 필요하나 정보를 가져오고 Domain Service 영역에서는 해당 Domain Infra만 접근하는 것이 더욱 합리적이라고 생각하여 리펙토링했습니다.

2023-07-07 22:00 UTC, chloe-codes1 approved these changes
리뷰 내용 반영된 것 확인했습니다 👍🏻 

naming이나 구조 관련해서 간단한 리뷰 추가로 드렸는데요,
이 부분만 수정되면 바로 merge 해도 좋을 것 같습니다!

고생 많으셨습니다!

2023-07-07 22:00 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/command/application/OrderService.java
> +    public void deleteOrder(DeleteOrderRequest deleteOrderRequest, UserId userId) {
application layer에서는 domain 특성에 맞게 cancelOrder 가 조금 더 적절할 것 같은데 한 번 고려해 주세요!

2023-07-07 22:00 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/command/application/OrderService.java
> +    public Order createOrder(UserId userId, StoreId storeId, List<ProductId> productsId,
여기도 placeOrder가 조금 더 주문이라는 domain에 맞을 것 같습니다!

2023-07-07 22:00 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/infra/persistence/imports/OrderJpaResponsibility.java
> +public interface OrderJpaResponsibility extends JpaRepository<Order, OrderId> {
interface 명 확인 한 번 부탁드립니다!

OrderJpaResponsibility -> OrderJpaRepository

2023-07-07 22:00 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/order/command/application/OrderCreateResponse.java
> +public class OrderCreateResponse extends RepresentationModel<OrderCreateResponse> {
Order가 생성되었을때의 응답이므로 OrderCreatedResponse는 어떨까요??

2023-07-07 22:00 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/query/application/CommentDaoFacade.java
> +public class CommentDaoFacade {
naming 확인 한 번 부탁드립니다!

CommentDaoFacade -> CommentFacade

2023-07-07 22:00 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/query/dto/CommentNode.java
> +    private String detail;
member 변수를 class 상단에 같이 위치시키는것이 좋아보입니다!

2023-07-07 22:00 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/query/dto/CommentNode.java
> +            List<CommentResponse> commentResponseByProductId) {
commentResponseByProductId 보다 commentResponses가 조금 더 좋아보입니다!

2023-07-07 22:00 UTC, chloe-codes1 commented on api/src/main/java/com/albert/commerce/comment/ui/CommentController.java
> +    private final StoreFacade storeFacade;
Controller에서 다른 aggregate의 facade를 직접 참조하는 것은 고민이 되는 부분이네요!

command와 query를 나눠서 설명드리자면 아래와 같은 구조가 좀 더 좋아보이는데요,

- command
  - service에서 다른 domain의 repository 참조
- query
  - facade에서 다른 domain의 facade 참조

이 부분은 EDA & CQRS 적용 후에 command와 query의 controller를 분리하면서 다시 개선할 수 있는 부분이라
일단은 생각하신 구조로 가고, 추후에 변경해도 좋을 것 같습니다!

2023-07-08 23:11 UTC, merged